export const ROUTER_ADDRESS_FIELD_CHANGED = 'ROUTER_ADDRESS_FIELD_CHANGED';
export const ROUTER_CREATE_JOB_REQUESTED = 'ROUTER_CREATE_JOB_REQUESTED';
export const ROUTER_CREATE_JOB_SUCCEEDED = 'ROUTER_CREATE_JOB_SUCCEEDED';
export const ROUTER_CREATE_JOB_FAILED = 'ROUTER_CREATE_JOB_FAILED';
