export const DOM_LOADED = 'DOM_LOADED';
export const POST_GEOCODE_REQUESTED = 'POST_GEOCODE_REQUESTED';
export const POST_GEOCODE_SUCCEEDED = 'POST_GEOCODE_SUCCEEDED';
export const POST_GEOCODE_FAILED = 'POST_GEOCODE_FAILED';
export const POST_JOBS_REQUESTED = 'POST_JOBS_REQUESTED';
export const POST_JOBS_SUCCEEDED = 'POST_JOBS_SUCCEEDED';
export const POST_JOBS_FAILED = 'POST_JOBS_FAILED';
